[2025-05-04T22:23:53.211+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-04T22:23:53.232+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tesla_stock_sentiment_final_etl.load_tweet_data manual__2025-05-04T22:23:49.851296+00:00 [queued]>
[2025-05-04T22:23:53.241+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tesla_stock_sentiment_final_etl.load_tweet_data manual__2025-05-04T22:23:49.851296+00:00 [queued]>
[2025-05-04T22:23:53.243+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-05-04T22:23:53.258+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load_tweet_data> on 2025-05-04 22:23:49.851296+00:00
[2025-05-04T22:23:53.266+0000] {standard_task_runner.py:72} INFO - Started process 6021 to run task
[2025-05-04T22:23:53.271+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tesla_stock_sentiment_final_etl', 'load_tweet_data', 'manual__2025-05-04T22:23:49.851296+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/tesla_stock_etl.py', '--cfg-path', '/tmp/tmp5ye094f0']
[2025-05-04T22:23:53.275+0000] {standard_task_runner.py:105} INFO - Job 28: Subtask load_tweet_data
[2025-05-04T22:23:53.563+0000] {task_command.py:467} INFO - Running <TaskInstance: tesla_stock_sentiment_final_etl.load_tweet_data manual__2025-05-04T22:23:49.851296+00:00 [running]> on host b3f6b00d0a7d
[2025-05-04T22:23:53.640+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tesla_stock_sentiment_final_etl' AIRFLOW_CTX_TASK_ID='load_tweet_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-04T22:23:49.851296+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-04T22:23:49.851296+00:00'
[2025-05-04T22:23:53.642+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-04T22:23:54.212+0000] {logging_mixin.py:190} INFO - df read
[2025-05-04T22:23:55.428+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-05-04T22:23:55.754+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-05-04T23:27:05.654+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-05-04T23:27:05.789+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-05-04T23:27:05.812+0000] {process_utils.py:132} INFO - Sending 15 to group 6021. PIDs of all processes in the group: [6021]
[2025-05-04T23:27:05.819+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 6021
[2025-05-04T23:27:05.848+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-04T23:27:07.582+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-04T23:27:07.817+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=6021, status='terminated', exitcode=0, started='22:23:52') (6021) terminated with exit code 0
